version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
#    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - app-network

  php:
    build:
      context: ./docker/php
      args:
        - USER_USERNAME
        - USER_UID
        - USER_GID
    volumes:
      - ./:/usr/share/bothelp:rw
    links:
      - redis
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:

volumes:
  redis-data:
    driver: local